### ISSUE TITLE
[1.21.1-NeoForge] Crash when joining world.

### ISSUE THREAD

**Issue by Gbergz** [TheFloydman/linking-books#1]
### What happened?
When joining a world with the mod installed, the game freezes upon joining and gets stuck at 100% progress.

```java.lang.IllegalArgumentException: Failed to serialize ResourceKey[linkingbooks:linkeffect / linkingbooks:intraage_linking]: Writing Link Effects to disk is currently not supported.```

### Versions
Minecraft: 1.21.1
NeoForge: 21.1.80
Linking Books: v0.7.2.0

### Error in logs: 
https://gist.githubusercontent.com/Gbergz/9e7311c808d736469e9345964c403e8d/raw/38d4a301a730bbe946d408f144b557bc9b96bf61/gistfile1.txt

**Comment by TheFloydman** [comment]
Without a more comprehensive log, it's hard to say exactly where the issue originates since I am unable to reproduce it. However, I needed to enable serialization in the Link Effect codec anyway, so this was a good reminder. :P Will you please try the attached jar and let me know if you still get the error?

[linkingbooks-1.21.1-0.7.2.1-neoforge.jar.zip](https://github.com/user-attachments/files/17985931/linkingbooks-1.21.1-0.7.2.1-neoforge.jar.zip)

**Comment by Gbergz** [comment]
The version you provided makes me able to join worlds again, no issues.

Fixed.
